# This workflow will build a package using Gradle and then publish it to GitHub packages when a release is created
# For more information see: https://github.com/actions/setup-java/blob/main/docs/advanced-usage.md#Publishing-using-gradle

name: Build

on:
  push:
    branches:
    - main
    paths:
      - "build.gradle"
      - "gradle.properties"
      - "src/**"  
  pull_request:
    branches:
    - main
    paths:
      - "build.gradle"
      - "gradle.properties"
      - "src/**"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Check out
      uses: actions/checkout@v2
    - name: Set up JDK 14
      uses: actions/setup-java@v2
      with:
        java-version: '14'
        distribution: 'adopt'
    - name: Set github number
      run: sed -i "s/undefined/$GITHUB_RUN_NUMBER/g" gradle.properties
    - name: Give permission
      run: chmod +x gradlew
    - name: Build with Gradle
      run: ./gradlew shadowJar
    - name: Save artifacts
      uses: actions/upload-artifact@v2
      with:
        name: build-artifacts
        path: build/libs/
